# Generated by Django 5.2.7 on 2025-11-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0002_category_remove_menuitem_inventory_menuitem_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='day_choice',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
