# Generated by Django 5.2.8 on 2025-11-16 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0003_menuitem_day_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='description',
            field=models.TextField(db_index=True, max_length=255, null=True),
        ),
    ]
